### ISSUE TITLE
Current line number in the editor is not visible

### ISSUE THREAD

**Issue by Drakelia** [T0uchM3/Cyberpunk-Theme#11]
Was just testing your theme and like it so far.
But I saw that the selected line number was not visible.

![image](https://user-images.githubusercontent.com/17825484/202688072-ce5c555a-203f-4b54-a18f-14838203bf0c.png)

I found that the last update (17.4) add a highlight feature so maybe it's related
https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#summary-of-whats-new-in-this-release-of-visual-studio-2022-version-174

![image](https://user-images.githubusercontent.com/17825484/202687192-60042cc3-a985-4933-a244-941cff329e65.png)

**Comment by T0uchM3** [comment]
Yeah, that seems like it. I'm still in 17.3 and the number is clear.
Thank you for reporting it and will look into it soon.
