### ISSUE TITLE
Low readability of inline hints

### ISSUE THREAD

**Issue by pyrocumulus** [T0uchM3/Cyberpunk-Theme#14]
**Problem**
I've been using this theme for quite a bit and I'm really liking it thus-far. I love the contrast it provides. However, there is one small area in which that contrast is lacking, and that's regarding inline hints:
![image](https://user-images.githubusercontent.com/1721382/229437829-1237b36a-abc9-47f7-923b-3b9c8301c97a.png)
_I don't usually use the hint for the inferred variable types (`var` keyword), but I do use them for the hints on lambda parameters. This was to further highlight the problem that users could face._

Depending on the type that is referred to in the inline hint, the readability of the hint can become incredibly low. As you can see `string` in this case is 'okay' to read but the `SocketSlashCommandDataOptions` really requires squinting before you can see what's going on.

**Suggested solution**
As for fixing this I think tweaking the light gray 'marking' colour would be best. I think a bit darker gray would be all that's needed.

**Additional information**
If you are unaware of how you can get those inline hints, they are in the C# Text editor options, under Advanced (scroll all the way down).
![image](https://user-images.githubusercontent.com/1721382/229439397-fadda630-9eab-4988-bacf-d738e2d96b81.png)

Mandatory environment information:
```
Visual Studio Community / Professional Edition Version 17.5.3
Cyberpunk Theme Version 2.2
Microsoft Windows 11 Pro Version	10.0.22621 Build 22621
```

**Comment by pyrocumulus** [comment]
I found another similar issue, but not with text.

On Windows 10 there appears to be no clear window border for the Quickwatch window:
![image](https://user-images.githubusercontent.com/1721382/229473889-9e9b27f2-62ec-4299-aa91-44df30c019fc.png)
Perhaps other tool windows have the same issue.

On Windows 11 I do get a border:
![image](https://user-images.githubusercontent.com/1721382/229474186-e9caf6d8-b5a5-4da6-b1fe-d33baf56945e.png)
I think it's because of the new W11 styling, the corners of the window are rounded as well.

I don't know if it's possible to fix this but it would be most helpful :)

**Comment by T0uchM3** [comment]
Thanks for reporting this, will look into it, may take a while tho (irl stuff).
Good description btw ;)

**Comment by pyrocumulus** [comment]
No problem! I know most end users of open-source things never bother to give feedback. I want to be one that does, but there's really no hurry. Real life always takes priority over open source :)

**Comment by h4zm1** [comment]
Will investigate the second problem soon.
