### ISSUE TITLE
Fix colors on vertical tabs?

### ISSUE THREAD

**Issue by adamskt** [T0uchM3/Cyberpunk-Theme#2]
I ❤️  this theme!

 Is there any way to make the colors, used by weirdos (such as myself) who like vertical tabs, match the rest of the UI colors?

![image](https://user-images.githubusercontent.com/105415/134590492-bfd5b36a-5af8-471b-aaf5-f0f2dd2c9740.png)

**Comment by T0uchM3** [comment]
Glad to hear you like it

**Comment by adamskt** [comment]
Yay!
![image](https://user-images.githubusercontent.com/105415/137610077-1176a08f-8770-4fa1-8528-5794245d2e25.png)
