### ISSUE TITLE
No color unless you hover it

### ISSUE THREAD

**Issue by LudovicoSforza** [T0uchM3/Cyberpunk-Theme#3]
There is no color in the search bar.
![image](https://user-images.githubusercontent.com/44255157/147381730-11b319c4-6098-495a-896a-71ce8fe39c0d.png)

**Comment by T0uchM3** [comment]
It's intended, the main search box in the menu bar share some color proprieties with other search bars like the one here.
Been pushing this aside for a while now anyway, and since this's the second remark I got this month about the search bar, I suppose it's about time to do something😄.
