### ISSUE TITLE
c# color in c++ file

### ISSUE THREAD

**Issue by dnhuy4869** [T0uchM3/Cyberpunk-Theme#4]
color of function and variable in .cs file is better. Can i use it in .cpp file ?

**Comment by T0uchM3** [comment]
It's not a problem of whether you can or not, it's whether you can do it without making the rest looking weird 😆.
Been thinking of redoing the c++ colors but just never find the time for it tbh.
Should be able to give it a go by next week or so.

**Comment by T0uchM3** [comment]
61c8631d80ab89d60472fc3905ee56c60e42f565
