### ISSUE TITLE
Resharper Conflicts.

### ISSUE THREAD

**Issue by Icebolt9000** [T0uchM3/Cyberpunk-Theme#5]
Resharper Conflicts with this theme could you fix these issues if ain't too much to ask.

**Comment by T0uchM3** [comment]
Not at all, I will try to get it out in a week or so.

**Comment by Icebolt9000** [comment]
Maybe you could look at R# it adds some more options to theme.
https://www.jetbrains.com/help/resharper/Coding_Assistance__Syntax_Highlighting.html

**Comment by T0uchM3** [comment]
I actually used R# (c++) before with syntax highlights, tried to make it look exactly like the theme I had (this one) but couldn't. I think it was missing something.

Last version I used was 21.3.2 btw and still the same.

But this's just nitpicking really lol, doesn't have to be an exact copy, will get into it soon.
