### ISSUE TITLE
MessageBoxes/Dialogues not really visible/need border color

### ISSUE THREAD

**Issue by bastianovic-dev** [T0uchM3/Cyberpunk-Theme#9]
Really love your theme! Thank you for creating!
Only thing I think should be improved: Dialogues need a more visible border for better distinction from the rest of the Visual Studio window.

Screenshot 1 (no border at all):

![pulling 2](https://user-images.githubusercontent.com/113640076/191124411-81c407b6-d090-4461-8e3b-5317de9e0e27.png)

Screenshot 2 (has border but not really visible nonetheless - needs pink border all around):

![pulling 1](https://user-images.githubusercontent.com/113640076/191124405-ca6b99ac-9a85-49b9-86bc-09d4c21a9ca4.png)

Just adding a pink border top, left, right, bottom would already be enough.

**Comment by T0uchM3** [comment]
I didn't really notice this till now, I'll be rolling out some changes soon.
Thanks for the feedback, and I'm glad you like it

**Comment by bastianovic-dev** [comment]
![grafik](https://user-images.githubusercontent.com/113640076/192105325-c92a9710-2bfe-45a5-ad99-e2fe38ff8598.png)

Looks great! Thank you very much!
